export const endpoints = {
  signup: '/auth/signup',
  login: '/auth/login',
  me: '/me',
  boards: '/boards',
  board: (id: string) => `/boards/${id}`,
  nodes: (boardId: string) => `/boards/${boardId}/nodes`,
  node: (id: string) => `/nodes/${id}`,
  edges: (boardId: string) => `/boards/${boardId}/edges`,
  edge: (id: string) => `/edges/${id}`,
  aiRun: '/ai/run',
  aiThreads: (boardId: string) => `/ai/threads?boardId=${boardId}`,
  aiThread: (id: string) => `/ai/threads/${id}/messages`,
  templates: '/templates',
  template: (id: string) => `/templates/${id}`,
  purchases: '/purchases',
  instantiate: (id: string, boardId: string) => `/templates/${id}/instantiate?boardId=${boardId}`,
  tasks: (boardId: string) => `/tasks?boardId=${boardId}`,
  task: (id: string) => `/tasks/${id}`,
};
